# Generated by Django 5.2 on 2025-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='material',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
